plugins {
  id("co.uzzu.dotenv.gradle") version "4.0.0"
}
ext.aerieVersion = '4.1.1'

allprojects {
  repositories {
    flatDir { dirs "$rootDir/third-party" }
    mavenCentral()
    maven {
      name = "GitHubPackages"
      url = "https://maven.pkg.github.com/nasa-ammos/aerie"
      credentials {
        username = env.GITHUB_USER.value
        password = env.GITHUB_TOKEN.value
      }
    }
  }
}

// Only apply java plugin to leaf subprojects (not the 'libraries' and 'examples' parent dirs)
subprojects {
  if (it.name == 'libraries' || it.name == 'examples') return

  apply plugin: 'java'

  java {
    toolchain {
      languageVersion = JavaLanguageVersion.of(21)
    }
  }

  dependencies {
    annotationProcessor "gov.nasa.jpl.aerie:merlin-framework-processor:${aerieVersion}"
    implementation "gov.nasa.jpl.aerie:contrib:${aerieVersion}"
    implementation "gov.nasa.jpl.aerie:merlin-framework:${aerieVersion}"
    implementation "gov.nasa.jpl.aerie:merlin-sdk:${aerieVersion}"
    compileOnly "gov.nasa.jpl.aerie:merlin-driver:${aerieVersion}"

    testImplementation "gov.nasa.jpl.aerie:merlin-framework-junit:${aerieVersion}"
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
  }

  test {
    useJUnitPlatform()
  }
}
