#!/usr/bin/env python3
"""Tests for bb_import.py, run against the REAL Blackbird export in fixtures/.

    python3 test_bb_import.py            # offline; no adapter, no JVM, no network
    python3 test_bb_import.py -v

The offline tests carry their own copy of the powermodel activity dictionary (captured from a live
`GET /introspect?model=powermodel`, see POWERMODEL_TYPES) so they never need the adapter. The one
test that does need it skips cleanly when it is unreachable.

The load-bearing test here is `TestParentRule`. Everything else fails loudly when it breaks; the
`parent == null` rule fails SILENTLY -- importing a decomposition child as a directive produces a
plan that loads, validates, and simulates, just with activities counted twice.
"""
import json
import os
import unittest
import urllib.error
import urllib.request
from datetime import datetime, timezone

import bb_import
from bb_import import ModelSchema, convert, coerce_value, map_kv_schema, us_to_pg_interval

HERE = os.path.dirname(os.path.abspath(__file__))
FIXTURE = os.path.join(HERE, "fixtures", "powermodel-export.plan.json")
ADAPTER_URL = os.environ.get("BB_ADAPTER_URL", "http://localhost:5011")

STRING = {"type": "string"}
DURATION = {"type": "duration"}
STRING_LIST = {"type": "series", "items": STRING}
STRING_MAP = {"type": "series", "items": {"type": "struct", "items": {"key": STRING, "value": STRING}}}

# Verbatim from `GET /introspect?model=powermodel` -- only the types the fixture uses, plus the two
# it exercises indirectly. `ActivityThree.d` is the model's one OPTIONAL parameter (default 1 min).
POWERMODEL_TYPES = {
    "SciencePass":    ([], {}, {}),
    "CollectScience": (["d"], {"d": DURATION}, {}),
    "Downlink":       (["d"], {"d": DURATION}, {}),
    "ActivityOne":    (["d"], {"d": DURATION}, {}),
    "ActivityTwo":    (["amount"], {"amount": {"type": "real"}}, {}),
    "ActivityThree":  (["d", "stringList"], {"d": DURATION, "stringList": STRING_LIST}, {"d": 60_000_000}),
    "ActivityFour":   (["d", "stringMap"], {"d": DURATION, "stringMap": STRING_MAP}, {}),
    "ActivityEight":  (["first", "second"], {"first": STRING, "second": STRING}, {}),
    "ActivityNine":   (["endTime"], {"endTime": STRING}, {}),
}

# What the fixture actually contains, restated here so the tests pin the file rather than read
# whatever it happens to say. 11 activities; the 4 with a non-null parent are decomposition spans.
EXPECTED_DROPS = {
    ("6f5c8b79-f2e1-4f72-9b41-5c670e81afcb", "CollectScience"),
    ("f86a845c-c650-4130-a408-cfd2322d1dd0", "Downlink"),
    ("1b4f113f-e588-4bd3-b617-6361d92712f8", "ActivityOne"),
    ("2b657162-aab7-467c-8297-9f45d4d6b77c", "ActivityOne"),
}
EXPECTED_DIRECTIVES = [
    ("SciencePass",   "01:00:00"),
    ("ActivityOne",   "02:00:00"),
    ("ActivityEight", "03:00:00"),
    ("ActivityTwo",   "04:00:00"),
    ("ActivityThree", "05:00:00"),
    ("ActivityFour",  "06:00:00"),
    ("ActivityNine",  "07:00:00"),
]


def stub_schema(types=None):
    s = ModelSchema("test stub")
    for typ, (order, schemas, defaults) in (types or POWERMODEL_TYPES).items():
        s.param_order[typ] = list(order)
        s.param_schemas[typ] = dict(schemas)
        # Mirrors ModelSchema.from_url: defaults are already in PlanDev's value space, so the
        # bbtype that effective_args uses to pick a coerce_default conversion is the pass-through.
        s.param_types[typ] = [(pn, "string") for pn in order]
        s.param_defaults[typ] = dict(defaults)
    return s


def load_fixture():
    with open(FIXTURE) as f:
        return json.load(f)


def convert_fixture(**kw):
    return convert(load_fixture(), stub_schema(), plan_name="powermodel-export", **kw)


class TestParentRule(unittest.TestCase):
    """The rule that has no downstream check: only `parent == null` becomes a directive.

    A decomposition child imported as a directive runs AND is regenerated by its parent. The plan
    still loads, still validates, still simulates -- it is just wrong, with no symptom. So the rule
    is pinned from both directions: nothing with a parent gets out, and the dropped set is exactly
    the set that has one.
    """

    def setUp(self):
        self.plan = load_fixture()
        self.transfer, self.report = convert(self.plan, stub_schema())
        self.by_id = {a["id"]: a for a in self.plan["activities"]}

    def test_no_child_is_ever_emitted(self):
        for a in self.transfer["activities"]:
            bb_id = a["metadata"]["blackbirdId"]
            self.assertIn(bb_id, self.by_id, "emitted an activity that is not in the source file")
            self.assertIsNone(self.by_id[bb_id]["parent"],
                              "emitted %s (%s), which is a decomposition child of %s"
                              % (a["type"], bb_id, self.by_id[bb_id]["parent"]))

    def test_dropped_set_is_exactly_the_non_null_parent_set(self):
        have_parent = {a["id"] for a in self.plan["activities"] if a.get("parent") is not None}
        self.assertEqual({d["id"] for d in self.report["dropped"]}, have_parent)
        for d in self.report["dropped"]:
            self.assertIn("decomposition child of", d["reason"])

    def test_every_top_level_activity_is_emitted(self):
        top = [a["id"] for a in self.plan["activities"] if a.get("parent") is None]
        self.assertEqual([a["metadata"]["blackbirdId"] for a in self.transfer["activities"]], top)

    def test_no_type_or_time_heuristic_could_have_worked(self):
        """Why `parent` and nothing else: the fixture is built so the alternatives all fail."""
        acts = self.plan["activities"]
        top_types = {a["type"] for a in acts if a.get("parent") is None}
        child_types = {a["type"] for a in acts if a.get("parent") is not None}
        self.assertTrue(top_types & child_types,
                        "fixture no longer has a type that is both a directive and a child")
        by_id = {a["id"]: a for a in acts}
        self.assertTrue(any(a["start"] == by_id[a["parent"]]["start"]
                            for a in acts if a.get("parent") in by_id),
                        "fixture no longer has a child starting at the same instant as its parent")


class TestCounts(unittest.TestCase):
    def test_seven_out_four_dropped(self):
        plan = load_fixture()
        transfer, report = convert(plan, stub_schema())
        self.assertEqual(len(plan["activities"]), 11)
        self.assertEqual(len(transfer["activities"]), 7)
        self.assertEqual(report["activities"], 7)
        self.assertEqual(len(report["dropped"]), 4)

    def test_dropped_are_exactly_the_expected_uuids_and_types(self):
        _, report = convert_fixture()
        self.assertEqual({(d["id"], d["type"]) for d in report["dropped"]}, EXPECTED_DROPS)

    def test_ids_are_sequential_and_index_aligned(self):
        transfer, _ = convert_fixture()
        self.assertEqual([a["id"] for a in transfer["activities"]], list(range(1, 8)))

    def test_constant_directive_fields(self):
        transfer, _ = convert_fixture()
        for a in transfer["activities"]:
            self.assertIsNone(a["anchor_id"])
            self.assertTrue(a["anchored_to_start"])
            self.assertEqual(a["tags"], [])
            self.assertEqual(a["name"], a["type"])
            self.assertEqual(set(a), {"anchor_id", "anchored_to_start", "arguments", "id",
                                      "metadata", "name", "start_offset", "tags", "type"})
        self.assertEqual(transfer["simulation_arguments"], {})

    def test_metadata_carries_the_blackbird_id_and_omits_empty_notes(self):
        plan = load_fixture()
        transfer, _ = convert(plan, stub_schema())
        top = [a for a in plan["activities"] if a.get("parent") is None]
        for directive, src in zip(transfer["activities"], top):
            self.assertEqual(directive["metadata"], {"blackbirdId": src["id"]})  # fixture notes are ""
        plan["activities"][0]["notes"] = "  keep me  "
        transfer, _ = convert(plan, stub_schema())
        self.assertEqual(transfer["activities"][0]["metadata"]["blackbirdNotes"], "  keep me  ")


class TestPlanWindow(unittest.TestCase):
    def test_plan_start_is_the_utc_day_floor_of_the_first_directive(self):
        _, report = convert_fixture()
        self.assertEqual(report["planStart"], "2024-01-01T00:00:00Z")

    def test_offsets_are_one_through_seven_hours_and_none_negative(self):
        transfer, _ = convert_fixture()
        self.assertEqual([(a["type"], a["start_offset"]) for a in transfer["activities"]],
                         EXPECTED_DIRECTIVES)
        for a in transfer["activities"]:
            self.assertFalse(a["start_offset"].startswith("-"), a["start_offset"])

    def test_suggested_duration_covers_the_last_directive_plus_a_day(self):
        _, report = convert_fixture()
        self.assertEqual(report["suggestedDuration"], "1 days 00:00:00")

    def test_transfer_prefills_the_import_dialog(self):
        """The gateway ignores these; PlanDev's UI reads them to prefill the form it does use."""
        transfer, _ = convert_fixture()
        self.assertEqual(transfer["start_time"], "2024-01-01T00:00:00+00:00")
        self.assertEqual(transfer["duration"], "1 days 00:00:00")
        self.assertEqual(transfer["name"], "powermodel-export")
        # `end_time` present is exactly how the UI detects a deprecated v1 transfer file.
        self.assertNotIn("end_time", transfer)

    def test_no_warnings_are_raised_about_the_window(self):
        _, report = convert_fixture()
        for w in report["warnings"]:
            self.assertNotIn("negative", w["message"])
            self.assertNotIn("beyond the end", w["message"])

    def test_plan_start_override_can_make_an_offset_negative_and_says_so(self):
        _, report = convert_fixture(plan_start=datetime(2024, 1, 1, 3, tzinfo=timezone.utc))
        self.assertTrue(any("negative" in w["message"] for w in report["warnings"]))
        transfer, _ = convert_fixture(plan_start=datetime(2024, 1, 1, 3, tzinfo=timezone.utc))
        self.assertEqual(transfer["activities"][0]["start_offset"], "-02:00:00")

    def test_duration_override_warns_about_activities_past_the_end(self):
        _, report = convert_fixture(duration_days=1,
                                    plan_start=datetime(2023, 12, 31, tzinfo=timezone.utc))
        self.assertTrue(any("beyond the end" in w["message"] for w in report["warnings"]))


class TestCoercion(unittest.TestCase):
    def setUp(self):
        transfer, self.report = convert_fixture()
        self.args = {a["type"]: a["arguments"] for a in transfer["activities"]}

    def test_duration_becomes_integer_microseconds(self):
        self.assertEqual(self.args["ActivityOne"], {"d": 3_600_000_000})           # 01:00:00.000000
        self.assertEqual(self.args["ActivityFour"]["d"], 600_000_000)              # 00:10:00.000000
        self.assertIsInstance(self.args["ActivityOne"]["d"], int)
        self.assertNotIsInstance(self.args["ActivityOne"]["d"], bool)

    def test_float_stays_a_number(self):
        self.assertEqual(self.args["ActivityTwo"], {"amount": 42.5})
        self.assertIsInstance(self.args["ActivityTwo"]["amount"], float)

    def test_string_stays_bare(self):
        self.assertEqual(self.args["ActivityEight"], {"first": "Earth", "second": "x"})

    def test_time_is_carried_verbatim_as_day_of_year(self):
        # NOT normalized to ISO-8601: Blackbird's own parser rejects that on the way back in.
        self.assertEqual(self.args["ActivityNine"], {"endTime": "2024-001T08:00:00.000000"})

    def test_list_of_string_stays_a_json_array(self):
        self.assertEqual(self.args["ActivityThree"]["stringList"], ["a", "b", "c"])

    def test_map_becomes_a_key_value_series(self):
        # Blackbird writes {"k1":"v1","k2":"v2"}; PlanDev/merlin's MapValueMapper wants this.
        self.assertEqual(self.args["ActivityFour"]["stringMap"],
                         [{"key": "k1", "value": "v1"}, {"key": "k2", "value": "v2"}])

    def test_no_argument_is_left_in_blackbird_shape(self):
        for typ, args in self.args.items():
            for name, value in args.items():
                self.assertNotIsInstance(value, dict, "%s.%s is still a native JSON map" % (typ, name))

    def test_arguments_follow_the_models_declared_order(self):
        self.assertEqual(list(self.args["ActivityEight"]), ["first", "second"])
        self.assertEqual(list(self.args["ActivityFour"]), ["d", "stringMap"])

    def test_the_only_fixture_warning_is_the_absolute_time_parameter(self):
        self.assertEqual(len(self.report["warnings"]), 1, self.report["warnings"])
        w = self.report["warnings"][0]
        self.assertEqual(w["type"], "ActivityNine")
        self.assertEqual(w["index"], 10)               # index in the SOURCE activities array
        self.assertIn("ABSOLUTE", w["message"])


class TestCoercionUnits(unittest.TestCase):
    def test_map_schema_detection(self):
        self.assertEqual(map_kv_schema(STRING_MAP), (STRING, STRING))
        self.assertIsNone(map_kv_schema(STRING_LIST))
        self.assertIsNone(map_kv_schema(STRING))

    def test_nested_containers_recurse(self):
        list_of_dur = {"type": "series", "items": DURATION}
        self.assertEqual(coerce_value(list_of_dur, ["00:00:01.000000", "1T00:00:00.000000"]),
                         [1_000_000, 86_400_000_000])
        map_to_list = {"type": "series", "items": {"type": "struct", "items": {
            "key": STRING, "value": STRING_LIST}}}
        self.assertEqual(coerce_value(map_to_list, {"k": ["a", "b"]}),
                         [{"key": "k", "value": ["a", "b"]}])

    def test_scalar_conversions(self):
        self.assertEqual(coerce_value({"type": "int"}, 3), 3)
        self.assertEqual(coerce_value({"type": "int"}, "3"), 3)
        self.assertIs(coerce_value({"type": "boolean"}, "true"), True)
        self.assertEqual(coerce_value({"type": "real"}, 1), 1.0)
        self.assertEqual(coerce_value({"type": "variant"}, "Idle"), "Idle")

    def test_bad_values_raise_rather_than_pass_through(self):
        for schema, value in [(DURATION, "not-a-duration"), (DURATION, {}),
                              (STRING_LIST, "a,b,c"), (STRING_MAP, ["k1"]),
                              ({"type": "int"}, "x"), ({"type": "boolean"}, 1), (STRING, 5)]:
            with self.assertRaises(bb_import.CoercionError):
                coerce_value(schema, value)

    def test_interval_formatting(self):
        self.assertEqual(us_to_pg_interval(0), "00:00:00")
        self.assertEqual(us_to_pg_interval(3_600_000_000), "01:00:00")
        self.assertEqual(us_to_pg_interval(1_500), "00:00:00.001500")
        self.assertEqual(us_to_pg_interval(90_061_000_000), "1 days 01:01:01")
        # Postgres signs every component; `-1 days 02:00:00` would read back as -22h.
        self.assertEqual(us_to_pg_interval(-90_000_000_000), "-1 days -01:00:00")


class TestWarningsAndDrops(unittest.TestCase):
    def test_unregistered_type_is_dropped(self):
        plan = load_fixture()
        plan["activities"][3]["type"] = "NotAThing"
        transfer, report = convert(plan, stub_schema())
        self.assertEqual(len(transfer["activities"]), 6)
        self.assertTrue(any(d["type"] == "NotAThing" and "not registered" in d["reason"]
                            for d in report["dropped"]))

    def test_undeclared_parameter_is_dropped_with_a_warning(self):
        plan = load_fixture()
        plan["activities"][3]["parameters"].append({"name": "bogus", "type": "string", "value": "z"})
        transfer, report = convert(plan, stub_schema())
        self.assertNotIn("bogus", transfer["activities"][1]["arguments"])
        self.assertTrue(any("'bogus' is not declared" in w["message"] for w in report["warnings"]))

    def test_absent_declared_parameter_is_filled_from_the_default(self):
        plan = load_fixture()
        three = next(a for a in plan["activities"] if a["type"] == "ActivityThree")
        three["parameters"] = [p for p in three["parameters"] if p["name"] != "d"]
        transfer, report = convert(plan, stub_schema())
        args = next(a["arguments"] for a in transfer["activities"] if a["type"] == "ActivityThree")
        self.assertEqual(args["d"], 60_000_000)
        self.assertTrue(any("filled from the model default" in w["message"] for w in report["warnings"]))

    def test_absent_declared_parameter_with_no_default_says_so(self):
        plan = load_fixture()
        one = next(a for a in plan["activities"] if a["type"] == "ActivityOne")
        one["parameters"] = []
        transfer, report = convert(plan, stub_schema())
        self.assertEqual(transfer["activities"][1]["arguments"], {})
        self.assertTrue(any("declares no default" in w["message"] for w in report["warnings"]))

    def test_uncoercible_value_warns_and_omits_the_argument(self):
        plan = load_fixture()
        one = next(a for a in plan["activities"] if a["type"] == "ActivityOne")
        one["parameters"][0]["value"] = "half past four"
        transfer, report = convert(plan, stub_schema())
        self.assertEqual(transfer["activities"][1]["arguments"], {})
        self.assertTrue(any("argument omitted" in w["message"] for w in report["warnings"]))

    def test_dangling_parent_uuid_warns_and_still_drops(self):
        plan = load_fixture()
        child = next(a for a in plan["activities"] if a["type"] == "CollectScience")
        child["parent"] = "00000000-0000-0000-0000-000000000000"
        transfer, report = convert(plan, stub_schema())
        self.assertEqual(len(transfer["activities"]), 7)
        self.assertTrue(any("not present in the file" in w["message"] for w in report["warnings"]))

    def test_duplicate_id_warns(self):
        plan = load_fixture()
        plan["activities"][3]["id"] = plan["activities"][4]["id"]
        _, report = convert(plan, stub_schema())
        self.assertTrue(any("appears more than once" in w["message"] for w in report["warnings"]))

    def test_model_drift_since_export_warns(self):
        """The file records the type each value was written as; a changed model must not be silent."""
        types = dict(POWERMODEL_TYPES)
        types["ActivityTwo"] = (["amount"], {"amount": {"type": "int"}}, {})
        _, report = convert(load_fixture(), stub_schema(types))
        self.assertTrue(any("declares schema" in w["message"] for w in report["warnings"]))

    def test_warning_index_is_the_source_index_not_the_output_index(self):
        plan = load_fixture()
        plan["activities"][10]["parameters"].append({"name": "nope", "type": "string", "value": "1"})
        _, report = convert(plan, stub_schema())
        self.assertEqual([w["index"] for w in report["warnings"] if "'nope'" in w["message"]], [10])

    def test_a_plan_with_no_activities_key_is_rejected(self):
        with self.assertRaises(ValueError):
            convert({}, stub_schema())

    def test_a_plan_of_only_children_needs_an_explicit_start(self):
        plan = {"activities": [a for a in load_fixture()["activities"] if a.get("parent")]}
        with self.assertRaises(ValueError):
            convert(plan, stub_schema())
        transfer, report = convert(plan, stub_schema(),
                                   plan_start=datetime(2024, 1, 1, tzinfo=timezone.utc))
        self.assertEqual(transfer["activities"], [])
        self.assertEqual(len(report["dropped"]), 4)


def adapter_reachable():
    try:
        urllib.request.urlopen(ADAPTER_URL + "/models", timeout=3).read()
        return True
    except Exception:
        return False


@unittest.skipUnless(adapter_reachable(), "no bb_service at %s" % ADAPTER_URL)
class TestAgainstLiveAdapter(unittest.TestCase):
    """Round trip: convert the fixture, then hand the directives back to Blackbird.

    Requires a running adapter, so it skips by default. Nothing above depends on it.
    """

    @classmethod
    def setUpClass(cls):
        cls.schema = ModelSchema.from_url(ADAPTER_URL, "powermodel")

    def test_live_introspection_matches_the_stubbed_dictionary(self):
        stub = stub_schema()
        for typ in POWERMODEL_TYPES:
            self.assertIn(typ, self.schema, "%s is no longer registered" % typ)
            self.assertEqual(self.schema.param_order[typ], stub.param_order[typ], typ)
            self.assertEqual(self.schema.param_schemas[typ], stub.param_schemas[typ], typ)
            self.assertEqual(self.schema.param_defaults[typ], stub.param_defaults[typ], typ)

    def test_converted_directives_simulate_back_to_eleven_spans(self):
        transfer, report = convert(load_fixture(), self.schema)
        directives = [{"id": a["id"], "type": a["type"], "arguments": a["arguments"],
                       "startOffset": bb_import.bb_dur_to_us(a["start_offset"].replace(" days ", "T"))}
                      for a in transfer["activities"]]
        req = urllib.request.Request(
            ADAPTER_URL + "/simulate?model=powermodel",
            data=json.dumps({"planStart": report["planStart"], "duration": 86_400_000_000,
                             "configuration": {}, "directives": directives}).encode(),
            headers={"Content-Type": "application/json"}, method="POST")
        with urllib.request.urlopen(req, timeout=300) as r:
            sim = json.load(r)
        self.assertNotIn("error", sim, sim.get("error"))
        spans = sim["spans"]
        # 7 directives + the 4 decomposition children the converter correctly refused to import.
        self.assertEqual(len(spans), 11, [s["type"] for s in spans])
        self.assertEqual(sorted(s["type"] for s in spans),
                         sorted([t for t, _ in EXPECTED_DIRECTIVES]
                                + ["CollectScience", "Downlink", "ActivityOne", "ActivityOne"]))
        self.assertEqual(sorted(s["directiveId"] for s in spans if s.get("directiveId")),
                         list(range(1, 8)))


if __name__ == "__main__":
    unittest.main()
