dependencies {
  // Procedural libraries (for test simulation utilities)
  annotationProcessor "gov.nasa.ammos.plandev.procedural:processor:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev.procedural:scheduling:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev.procedural:timeline:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev.procedural:constraints:${plandevVersion}"

  implementation "gov.nasa.ammos.plandev:merlin-driver:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev:parsing-utilities:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev:type-utils:${plandevVersion}"

  // Stateless simulation utilities
  implementation "gov.nasa.ammos.plandev.procedural:utils:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev:orchestration-utils:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev:permissions:${plandevVersion}"

  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

jar {
  dependsOn configurations.runtimeClasspath
  from {
    configurations.runtimeClasspath.filter { it.exists() }.collect { it.isDirectory() ? it : zipTree(it) }
  }
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
  archiveFileName.set("testing-patterns-example.jar")
}
