dependencies {
  // Procedural scheduling and constraints
  annotationProcessor "gov.nasa.ammos.plandev.procedural:processor:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev.procedural:scheduling:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev.procedural:timeline:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev.procedural:constraints:${plandevVersion}"

  // Required for Duration, SerializedValue in scheduling goals
  implementation "gov.nasa.ammos.plandev:merlin-framework:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev:contrib:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev:type-utils:${plandevVersion}"
}

jar {
  archiveFileName.set("constraints-scheduling-procedures.jar")
}
