dependencies {
  // Procedural scheduling
  annotationProcessor "gov.nasa.ammos.aerie.procedural:processor:${aerieVersion}"
  implementation "gov.nasa.ammos.aerie.procedural:scheduling:${aerieVersion}"
  implementation "gov.nasa.ammos.aerie.procedural:timeline:${aerieVersion}"
  implementation "gov.nasa.ammos.aerie.procedural:constraints:${aerieVersion}"

  // Required for Duration, SerializedValue in scheduling goals
  implementation "gov.nasa.jpl.aerie:merlin-framework:${aerieVersion}"
  implementation "gov.nasa.jpl.aerie:contrib:${aerieVersion}"
  implementation "gov.nasa.jpl.aerie:type-utils:${aerieVersion}"
}

jar {
  archiveFileName.set("external-events-procedures.jar")
}
