dependencies {
  implementation project(':libraries:power')
  implementation project(':libraries:data')

  // Procedural scheduling and constraints
  annotationProcessor "gov.nasa.ammos.aerie.procedural:processor:${aerieVersion}"
  implementation "gov.nasa.ammos.aerie.procedural:scheduling:${aerieVersion}"
  implementation "gov.nasa.ammos.aerie.procedural:timeline:${aerieVersion}"
  implementation "gov.nasa.ammos.aerie.procedural:constraints:${aerieVersion}"

  // Required by procedural scheduling
  implementation "gov.nasa.jpl.aerie:type-utils:${aerieVersion}"
}

// Include library sources for annotation processor
sourceSets {
  main {
    java {
      srcDir project(':libraries:power').file('src/main/java')
      srcDir project(':libraries:data').file('src/main/java')
    }
  }
}

// Fat JAR for uploading to Aerie
jar {
  dependsOn configurations.runtimeClasspath
  from {
    configurations.runtimeClasspath.filter { it.exists() }.collect { it.isDirectory() ? it : zipTree(it) }
  }
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
  archiveFileName.set("constraints-scheduling-example.jar")
}
