import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
  id 'io.github.goooler.shadow' version '8.1.7'
}

dependencies {
  // Procedural scheduling
  annotationProcessor "gov.nasa.ammos.plandev.procedural:processor:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev.procedural:scheduling:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev.procedural:timeline:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev.procedural:constraints:${plandevVersion}"

  // Required for Duration, SerializedValue in scheduling goals
  implementation "gov.nasa.ammos.plandev:merlin-framework:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev:contrib:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev:type-utils:${plandevVersion}"
}

tasks.named('jar') {
  enabled = false
}
