import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
  id 'java'
  id 'io.github.goooler.shadow' version '8.1.7'
}

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

dependencies {
  // Pull in mission model classes (for activity/resource type references)
  implementation project(':examples:05-orbiter')

  // Procedural constraint libraries
  annotationProcessor "gov.nasa.ammos.plandev.procedural:processor:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev.procedural:scheduling:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev.procedural:timeline:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev.procedural:constraints:${plandevVersion}"

  // Standard Aerie deps
  implementation "gov.nasa.ammos.plandev:merlin-framework:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev:contrib:${plandevVersion}"
  implementation "gov.nasa.ammos.plandev:type-utils:${plandevVersion}"
}

tasks.register('buildAllConstraintProcedureJars') {
  group = 'ConstraintProcedureJars'

  dependsOn "generateConstraintProcedureJarTasks"
  dependsOn {
    tasks.findAll { task -> task.name.startsWith('buildConstraintProcedureJar_') }
  }
}

tasks.create("generateConstraintProcedureJarTasks") {
  group = 'ConstraintProcedureJars'

  final proceduresDir = findFirstMatchingBuildDir("generated/procedures")

  if (proceduresDir == null) {
    println "No procedures folder found"
    return
  }
  println "Generating jar tasks for the following procedures directory: ${proceduresDir}"

  final files = file(proceduresDir).listFiles()
  if (files.length == 0) {
    println "No procedures available within folder ${proceduresDir}"
    return
  }

  files.toList().each { file ->
    final nameWithoutExtension = file.name.replace(".java", "")
    final taskName = "buildConstraintProcedureJar_${nameWithoutExtension}"

    println "Generating ${taskName} task, which will build ${nameWithoutExtension}.jar"

    tasks.register(taskName, ShadowJar) {
      group = 'ConstraintProcedureJars'
      configurations = [project.configurations.compileClasspath, project.configurations.runtimeClasspath]
      from sourceSets.main.output
      archiveBaseName = ""
      archiveClassifier.set(nameWithoutExtension)
      manifest {
        attributes 'Main-Class': getMainClassFromGeneratedFile(file)
      }
      minimize()
    }
  }
}

private String findFirstMatchingBuildDir(String pattern) {
  String found = null
  final generatedDir = file("build/generated/sources")
  generatedDir.mkdirs()
  generatedDir.eachDirRecurse { dir -> if (dir.path.contains(pattern)) found = dir.path }
  return found
}

private static String getMainClassFromGeneratedFile(File file) {
  final fileString = file.toString()
  final prefix = "build/generated/sources/annotationProcessor/java/main/"
  final index = fileString.indexOf(prefix) + prefix.length()
  final trimmed = fileString.substring(index).replace(".java", "")
  return trimmed.replace("/", ".")
}
